# Generated by Django 4.1.7 on 2023-04-12 16:35

from django.db import migrations
import employees.models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rate',
            field=enumchoicefield.fields.EnumChoiceField(default=employees.models.Rate(1), enum_class=employees.models.Rate, max_length=5),
        ),
    ]
