# Generated by Django 4.1.7 on 2023-03-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='position',
            new_name='employee',
        ),
    ]
