# Generated by Django 4.1.7 on 2023-03-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_position_account_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
