# Generated by Django 4.1.7 on 2023-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_email_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
