# Generated by Django 4.1.7 on 2023-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customercontractfile_customercontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontractfile',
            name='contract_file',
            field=models.FileField(upload_to='documents/customers/customer_contract_files'),
        ),
    ]
