# Generated by Django 4.1.7 on 2023-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customercontractfile_contract_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontract',
            name='contracts',
        ),
        migrations.AddField(
            model_name='customercontract',
            name='contract_file',
            field=models.FileField(null=True, upload_to='documents/customers/customer_contract_files'),
        ),
        migrations.DeleteModel(
            name='CustomerContractFile',
        ),
    ]
