# Generated by Django 4.1.7 on 2023-03-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_employees_employee_and_more'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='assigned_supervisor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
