# Generated by Django 4.1.7 on 2023-04-11 21:29

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import inventory_orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0003_requiredobjectinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('status', enumchoicefield.fields.EnumChoiceField(default=inventory_orders.models.InventoryOrderStatus(1), enum_class=inventory_orders.models.InventoryOrderStatus, max_length=11)),
                ('in_progress_time', models.DateTimeField(null=True)),
                ('completed_time', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('inventory_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_orders.inventoryorder')),
                ('required_object_inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.requiredobjectinventory')),
            ],
        ),
    ]
