# Generated by Django 4.1.7 on 2023-04-16 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_requiredobjectinventory'),
        ('inventory_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='object_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.object'),
        ),
    ]
