# Generated by Django 4.1.7 on 2023-03-22 09:53

from django.db import migrations
import enumchoicefield.fields
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=orders.models.CleaningOrderStatus['PLANNED'], enum_class=orders.models.CleaningOrderStatus, max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(default=orders.models.CleaningOrderType['OTHER'], enum_class=orders.models.CleaningOrderType, max_length=9),
        ),
    ]
