# Generated by Django 4.1.7 on 2023-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_employees_employee_and_more'),
        ('orders', '0007_alter_order_status_alter_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, to='employees.employee'),
        ),
    ]
