# Generated by Django 4.1.7 on 2023-03-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_assigned_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='accept_time',
            new_name='confirmed_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_when',
            new_name='start_time',
        ),
    ]
