# Generated by Django 4.1.7 on 2023-03-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_accept_time_order_confirmed_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
