# Generated by Django 4.1.7 on 2023-04-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderattachmentsevidence_orderattachments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderAttachments',
            new_name='OrderAttachment',
        ),
        migrations.RenameModel(
            old_name='OrderAttachmentsEvidence',
            new_name='OrderAttachmentEvidence',
        ),
    ]
