# Generated by Django 4.1.7 on 2023-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_orderattachments_orderattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderemployee',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
